# Generated by Django 2.2.2 on 2019-07-05 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'zip'])])),
                ('email', models.EmailField(max_length=64)),
                ('max_context_lines', models.IntegerField()),
                ('request_time', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='new', max_length=30)),
            ],
        ),
    ]
