# Generated by Django 2.1 on 2019-04-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=64)),
                ('input_file', models.FileField(upload_to='./bin/inputFile/Result')),
                ('conf_file', models.FileField(upload_to='./bin/conf_file/')),
                ('request_time', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='new', max_length=30)),
            ],
        ),
    ]
