# Generated by Django 2.2.2 on 2019-07-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='max_context_lines',
            field=models.IntegerField(default=0),
        ),
    ]
