# Generated by Django 2.1 on 2019-04-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190416_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='conf_file',
            field=models.FileField(upload_to='./'),
        ),
        migrations.AlterField(
            model_name='request',
            name='input_file',
            field=models.FileField(upload_to='./'),
        ),
    ]
