# Generated by Django 2.2.2 on 2019-07-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190705_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='min_context_lines',
            field=models.IntegerField(default=0),
        ),
    ]
