# Generated by Django 2.2.2 on 2019-07-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_request_min_context_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='input_nonsensical_distractors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='input_plau_distractors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='input_ungram_distractors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='nonsen_kid_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='nonsen_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='output_plau_distractor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='output_ungram_distractor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='plau_kid_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='plau_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='ungram_kid_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='ungram_num',
            field=models.IntegerField(default=0),
        ),
    ]
